repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "0.9.2"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix, lf]
  - repo: local
    hooks:
      - id: run-tests
        name: run-tests
        entry: pytest --without-integration tests
        language: python
        additional_dependencies:
          [
            pre-commit,
            pytest,
            pytest-integration,
            pytest-mock,
            pytest-timeout,
            grpcio,
            protobuf,
          ]
        always_run: true
        pass_filenames: false
